[package]
name = "gltsv"
version = "0.1.0"
authors = ["James Welchman <jamesw@ems.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"